/*
	Colors for Cops And Robbers script
	Scripted by Arose Niazi.
	Scripting started on 18th October 2017
	Last Updated: ----
	
	Credits:
		color-hex.com
		
	Functions:
		
	Functions Being Called:
		
*/

#define COL_SERVER "{39a1c3}"
#define COLOR_SERVER 0x39a1c375
#define IRC_SERVER_COLOR "1,7"

#define COL_SERVER_INFO "{ffc220}"
#define COLOR_SERVER_INFO 0xffc22075

#define COL_WHITE "{FFFFFF}"
#define COLOR_WHITE 0xFFFFFF75


#define COL_LIGHTBLUE "{00B6FF}"
#define COL_RED "{FF0000}"
#define COL_GREEN "{99FF00}"
#define COL_SKYBLUE "{00B6FF}"
#define COL_PURPLE "{800080}"
#define COL_ORANGE "{FF7519}"
#define COL_WHITE "{FFFFFF}"
#define COL_YELLOW "{FFFF00}"
#define COL_BLUE "{4285f4}"

#define COLOR_ERROR COLOR_RED
#define IRC_ERROR_COLOR "0,4"

#define COLOR_RED 0xFF000075

#define IRC_SPECIAL_COLOR "0,1"

#define IRC_ADMIN_COLOR_INFO "6,8"
#define COLOR_ADMIN_INFO 0xd8b2d875
#define COL_ADMIN_INFO "{d8b2d8}"

#define COLOR_CONNECT 0xFD7C6E75
#define IRC_CONNECT_COLOR "7,1"

#define IRC_NORMAL_COLOR "12"

#define COLOR_DJ COLOR_PASTEL_PINK
#define IRC_COLOR_DJ "13,1"


#define IRC_RADIO_COLOR "10"

#define IRC_LIST_COLOR "8,7"

#define COLOR_PASTEL_PINK 0xFFB6C175